### ISSUE TITLE
Deploy CDOJ in nginx

### ISSUE THREAD

**Issue by WallE256** [UESTC-ACM/CDOJ#288]
Hello again, I would need some help in deploying CDOJ to another "folder" (I mean, example.com/oj instead of example.com). ATM, I have nginx as a reverse proxy on location "/oj", but that doesn't work out as expected. What do I need to do?

**Comment by lyhypacm** [comment]
The simplest way to deploy OJ to your server is run `gradle war` and deploy your own war file.

Note: you need to use symbolic link to link resources folder to another location so that you can deploy the project again.

you can find resources folders in `trunk/gradle.properties`, mainly including:
- `imagesPath`
- `dataPath`
- `uploadPath`
- `judgeWorkPath`

**Comment by WallE256** [comment]
Where do I actually need to make the symbolic links, in a jetty server? (Directory tree: http://pastebin.com/eJYEa6t4 )

**Comment by lyhypacm** [comment]
I think you need to find some resource about how to handle website resources maintained by `ngnix`.

You can put all of the 4 folders in your own location(e.g. on the home folder of the user, or some other places), and link actual folders to the git project root.

For example:
```bash
# move real folders to your own location, e.g. ~/cdoj/
git-project-root$ mv data/data static/images data/upload work ~/cdoj/
git-project-root$ ln -s ~/cdoj/data data/data
git-project-root$ ln -s ~/cdoj/images static/images
git-project-root$ ln -s ~/cdoj/upload data/upload
git-project-root$ ln -s ~/cdoj/work work
```

**Comment by WallE256** [comment]
Contacting you by email with more sensible information. Closed.
